services:
  - type: web
    name: chronuswebsite
    runtime: php
    rootDir: .
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:10000 -t .
    plan: free
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
